# Generated by Django 5.1.3 on 2024-11-20 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id_processo', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='pdfs/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('partes', models.JSONField(blank=True, null=True)),
                ('demandas', models.JSONField(blank=True, null=True)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
