# Generated by Django 5.1.3 on 2024-11-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='usuario',
        ),
    ]
